export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';
export const NEW_GAME = 'NEW_GAME';
export const MONSTER_NO_CATCH = 'MONSTER_NO_CATCH';
export const REMOVE_OLD_SESSIONS = 'REMOVE_OLD_SESSIONS' ;
export const NEW_PLAYER = 'NEW_PLAYER';
export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION';
export const PLAYER_DISCONNECT = 'PLAYER_DISCONNECT';
